[package]
name = "twasm-utils"
version = "0.6.1"
authors = ["Nikolay Volf <nikvolf@gmail.com>", "Sergey Pepyakin <s.pepyakin@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Collection of command-line utilities and corresponding Rust api for producing twasm-compatible executables"
keywords = ["wasm", "webassembly", "pwasm"]

[dependencies]
tetsy-wasm = { version = "0.31", default-features = false }
log = { version = "0.4", default-features = false }
byteorder = { version = "1", default-features = false }

[dev-dependencies]
tempdir = "0.3"
wabt = "0.2"
diff = "0.1.11"

[features]
default = ["std"]
std = ["tetsy-wasm/std", "log/std", "byteorder/std"]

[workspace]
members = [
  "./cli",
]
