[package]
name = "twasm-utils"
version = "0.16.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>", "Sergey Pepyakin <s.pepyakin@gmail.com>"]
description = "Collection of command-line utilities and corresponding Rust api for producing twasm-compatible executables"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/twasm-utils"
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"


[[bin]]
name = "wasm-prune"
path = "cli/prune/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-ext"
path = "cli/ext/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-gas"
path = "cli/gas/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-build"
path = "cli/build/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-stack-height"
path = "cli/stack_height/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-pack"
path = "cli/pack/main.rs"
required-features = ["cli"]

[[bin]]
name = "wasm-check"
path = "cli/check/main.rs"
required-features = ["cli"]

[dependencies]
# If you add the feature "bulk", make sure you fixed all expects that say
# "tetsy-wasm is compiled without bulk-memory operations"
tetsy-wasm = { version = "0.41.0", default-features = false }
log = { version = "0.4", default-features = false }
byteorder = { version = "1", default-features = false }

# Dependencies only used by the binaries
glob = { version = "0.2", optional = true }
clap = { version = "2.24", optional = true }
env_logger = { version = "0.5", optional = true }
lazy_static = { version = "1.0", optional = true }

[dev-dependencies]
tempdir = "0.3"
wabt = "0.10"
diff = "0.1.11"
indoc = "0.3"
rand = "0.7"
binaryen = "0.8"

[features]
default = ["std"]
std = ["tetsy-wasm/std", "log/std", "byteorder/std"]
cli = [
  "std",
  "glob",
  "clap",
  "env_logger",
  "lazy_static",
]
